In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("C:/Users/HP/Downloads/messy_customer_sales_data.csv")
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52,KOLKATA,26-06-2025,17-05-2025,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,17-02-2021,22-07-2025,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62,hyderabad,05-11-2023,08-12-2024,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40,hyderabad,13-03-2022,02-10-2025,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41,CHENNAI,05-04-2024,15-12-2024,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10195,CUST10767,Robert Lewis,female,35.0 years,delhi,08-12-2020,25-01-2025,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10196,NaN,Diane Evans,M,53,bangalore,31-12-2023,07-05-2025,11639.0,7.0,lisadennis@example.net,5200349941,IND
10197,CUST6315,Joshua Martinez,m,25,hyderabad,15-02-2022,11-01-2025,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55,NaN,16-03-2021,14-05-2025,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34,HYDERABAD,12-10-2020,27-06-2025,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [5]:
df.shape

(10200, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                10200 non-null  object
 2   Gender              9174 non-null   object
 3   Age                 9249 non-null   object
 4   City                9184 non-null   object
 5   Signup_Date         10200 non-null  object
 6   Last_Purchase_Date  9188 non-null   object
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  object
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 956.4+ KB

In [8]:
df.describe().round()

       Purchase_Amount  Feedback_Score  Phone_Number
count           9179.0          9177.0  1.020000e+04
mean           29090.0             5.0  4.979974e+09
std           208697.0             3.0  2.902593e+09
min             -500.0             1.0  9.208990e+05
25%            12295.0             3.0  2.449157e+09
50%            24330.0             5.0  4.988639e+09
75%            37130.0             8.0  7.510448e+09
max          9999999.0            10.0  9.994402e+09

In [9]:
df.isnull().sum()

Customer_ID           1023
Name                     0
Gender                1026
Age                    951
City                  1016
Signup_Date              0
Last_Purchase_Date    1012
Purchase_Amount       1021
Feedback_Score        1023
Email                    0
Phone_Number             0
Country                732
dtype: int64

In [14]:
df[df.duplicated()]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,01-12-2023,04-11-2024,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51,NaN,20-04-2025,28-02-2025,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51,Bangalore,14-08-2023,01-11-2024,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46,Chennai,22-11-2023,21-03-2025,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46,Chennai,18-04-2021,10-10-2024,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34,chennai,11-09-2022,13-03-2025,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23,Kolkata,09-12-2023,28-10-2024,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56,NaN,18-02-2023,14-12-2024,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26,Mumbai,21-05-2022,17-06-2025,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44,MUMBAI,17-05-2023,12-07-2025,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42,Bangalore,31-07-2025,21-09-2025,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33,Kolkata,21-10-2022,24-04-2025,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43,Delhi,16-04-2021,13-01-2025,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51,Hyderabad,28-03-2021,22-01-2025,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61,Bangalore,05-11-2023,10-01-2025,40711.0,8.0,kellifox@example.com,5600790669,India

In [15]:
for i in df.columns:
    if df[i].nunique()<20:
        print(df[i].value_counts())
        print("-"*50)

Gender
f         1184
M         1171
m         1163
F         1157
MALE      1131
female    1128
male      1121
FEMALE    1119
Name: count, dtype: int64
--------------------------------------------------
City
Kolkata       820
Mumbai        812
Chennai       784
Bangalore     773
Hyderabad     770
Delhi         763
CHENNAI       404
KOLKATA       395
MUMBAI        393
hyderabad     384
bangalore     383
DELHI         378
delhi         369
BANGALORE     363
HYDERABAD     360
mumbai        352
chennai       343
kolkata       338
Name: count, dtype: int64
--------------------------------------------------
Feedback_Score
2.0     952
4.0     947
7.0     938
6.0     927
3.0     913
8.0     912
1.0     907
9.0     903
10.0    901
5.0     877
Name: count, dtype: int64
--------------------------------------------------
Country
India    7132
IND       793
india     772
InDia     771
Name: count, dtype: int64
--------------------------------------------------

**Handling Missing Values**

In [16]:
df.isnull().sum()

Customer_ID           1023
Name                     0
Gender                1026
Age                    951
City                  1016
Signup_Date              0
Last_Purchase_Date    1012
Purchase_Amount       1021
Feedback_Score        1023
Email                    0
Phone_Number             0
Country                732
dtype: int64

In [18]:
df.dropna(subset = ["Customer_ID"],inplace=True)

In [19]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [21]:
df["Age"].unique()

array(['52', '51.0 years', '62', '40', '41', nan, '18', '43.0 years',
       '40.0 years', '26', '32', '22', '59', '65', '61', '31',
       '54.0 years', '55', '69', '61.0 years', '24', '63', '19', '50',
       '56', '36', '68', '43', '38', '27', '57.0 years', '23', '25', '66',
       '28', '30', '46', '48', '20', '37', '67', '51', '35', '58', '29',
       'nan years', '39', '49', '47', '42', '44', '64', '53', '60',
       '59.0 years', '45', '21', '34', '54', '48.0 years', '46.0 years',
       '33', '57', '30.0 years', '58.0 years', '35.0 years', '34.0 years',
       '69.0 years', '250', '19.0 years', '27.0 years', '53.0 years',
       '65.0 years', '66.0 years', '44.0 years', '49.0 years',
       '25.0 years', '23.0 years', '62.0 years', '41.0 years',
       '33.0 years', '28.0 years', '22.0 years', '20.0 years',
       '42.0 years', '45.0 years', '3', '63.0 years', '37.0 years',
       '38.0 years', '55.0 years', '18.0 years', '36.0 years',
       '67.0 years', '29.0 years', '39.0 years', '31.0 years',
       '47.0 years', '52.0 years', '-10', '60.0 years', '24.0 years',
       '26.0 years', '21.0 years', '64.0 years', '50.0 years',
       '68.0 years', '32.0 years', '56.0 years'], dtype=object)

In [22]:
df['Age'] = df['Age'].str.replace(" years","",regex = False)

In [23]:
df["Age"].unique()

array(['52', '51.0', '62', '40', '41', nan, '18', '43.0', '40.0', '26',
       '32', '22', '59', '65', '61', '31', '54.0', '55', '69', '61.0',
       '24', '63', '19', '50', '56', '36', '68', '43', '38', '27', '57.0',
       '23', '25', '66', '28', '30', '46', '48', '20', '37', '67', '51',
       '35', '58', '29', 'nan', '39', '49', '47', '42', '44', '64', '53',
       '60', '59.0', '45', '21', '34', '54', '48.0', '46.0', '33', '57',
       '30.0', '58.0', '35.0', '34.0', '69.0', '250', '19.0', '27.0',
       '53.0', '65.0', '66.0', '44.0', '49.0', '25.0', '23.0', '62.0',
       '41.0', '33.0', '28.0', '22.0', '20.0', '42.0', '45.0', '3',
       '63.0', '37.0', '38.0', '55.0', '18.0', '36.0', '67.0', '29.0',
       '39.0', '31.0', '47.0', '52.0', '-10', '60.0', '24.0', '26.0',
       '21.0', '64.0', '50.0', '68.0', '32.0', '56.0'], dtype=object)

In [27]:
df['Age'] = pd.to_numeric(df['Age'], errors = "coerce")

In [28]:
df.loc[(df['Age'] <0) | (df['Age']>100), "Age"] = None

In [29]:
df["Age"].unique()

array([52., 51., 62., 40., 41., nan, 18., 43., 26., 32., 22., 59., 65.,
       61., 31., 54., 55., 69., 24., 63., 19., 50., 56., 36., 68., 38.,
       27., 57., 23., 25., 66., 28., 30., 46., 48., 20., 37., 67., 35.,
       58., 29., 39., 49., 47., 42., 44., 64., 53., 60., 45., 21., 34.,
       33.,  3.])

In [31]:
median_age = int(df["Age"].median())
median_age

43

In [32]:
df["Age"].fillna(median_age)

0        52.0
1        51.0
2        62.0
3        40.0
4        41.0
         ...
10194    40.0
10195    35.0
10197    25.0
10198    55.0
10199    34.0
Name: Age, Length: 9177, dtype: float64

In [33]:
df["Age"].unique()

array([52., 51., 62., 40., 41., nan, 18., 43., 26., 32., 22., 59., 65.,
       61., 31., 54., 55., 69., 24., 63., 19., 50., 56., 36., 68., 38.,
       27., 57., 23., 25., 66., 28., 30., 46., 48., 20., 37., 67., 35.,
       58., 29., 39., 49., 47., 42., 44., 64., 53., 60., 45., 21., 34.,
       33.,  3.])

In [34]:
df["Age"] = df["Age"].fillna(median_age)

In [35]:
df["Age"].unique()

array([52., 51., 62., 40., 41., 43., 18., 26., 32., 22., 59., 65., 61.,
       31., 54., 55., 69., 24., 63., 19., 50., 56., 36., 68., 38., 27.,
       57., 23., 25., 66., 28., 30., 46., 48., 20., 37., 67., 35., 58.,
       29., 39., 49., 47., 42., 44., 64., 53., 60., 45., 21., 34., 33.,
        3.])

In [36]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [37]:
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,26-06-2025,17-05-2025,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0,NaN,17-02-2021,22-07-2025,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,05-11-2023,08-12-2024,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,13-03-2022,02-10-2025,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,05-04-2024,15-12-2024,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10194,CUST6146,Cody Thompson,f,40.0,NaN,21-08-2024,26-10-2024,35101.0,1.0,mitchellrivera@example.net,6380823112,India
10195,CUST10767,Robert Lewis,female,35.0,delhi,08-12-2020,25-01-2025,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10197,CUST6315,Joshua Martinez,m,25.0,hyderabad,15-02-2022,11-01-2025,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55.0,NaN,16-03-2021,14-05-2025,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34.0,HYDERABAD,12-10-2020,27-06-2025,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [40]:
df['City'].unique()

array([' KOLKATA ', nan, ' hyderabad ', ' CHENNAI ', ' kolkata ',
       ' BANGALORE ', ' Hyderabad ', ' HYDERABAD ', ' Mumbai ',
       ' chennai ', ' Delhi ', ' bangalore ', ' Bangalore ', ' Kolkata ',
       ' delhi ', ' Chennai ', ' MUMBAI ', ' DELHI ', ' mumbai '],
      dtype=object)

In [41]:
median_amt = df['Purchase_Amount'].median()
median_amt

24268.0

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9177 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                9177 non-null   object
 2   Gender              8243 non-null   object
 3   Age                 9177 non-null   float64
 4   City                8259 non-null   object
 5   Signup_Date         9177 non-null   object
 6   Last_Purchase_Date  8263 non-null   object
 7   Purchase_Amount     9177 non-null   float64
 8   Feedback_Score      8272 non-null   float64
 9   Email               9177 non-null   object
 10  Phone_Number        9177 non-null   int64
 11  Country             8513 non-null   object
dtypes: float64(3), int64(1), object(8)
memory usage: 932.0+ KB

In [45]:
df['Purchase_Amount'] = df['Purchase_Amount'].fillna(median_amt)

In [46]:
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,26-06-2025,17-05-2025,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0,NaN,17-02-2021,22-07-2025,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,05-11-2023,08-12-2024,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,13-03-2022,02-10-2025,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,05-04-2024,15-12-2024,24268.0,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10194,CUST6146,Cody Thompson,f,40.0,NaN,21-08-2024,26-10-2024,35101.0,1.0,mitchellrivera@example.net,6380823112,India
10195,CUST10767,Robert Lewis,female,35.0,delhi,08-12-2020,25-01-2025,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10197,CUST6315,Joshua Martinez,m,25.0,hyderabad,15-02-2022,11-01-2025,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55.0,NaN,16-03-2021,14-05-2025,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34.0,HYDERABAD,12-10-2020,27-06-2025,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [47]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [54]:
feedback_mode = df['Feedback_Score'].mode()[0]
feedback_mode

np.float64(2.0)

In [55]:
df['Feedback_Score'] = df['Feedback_Score'].fillna(feedback_mode)

In [56]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                     0
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount         0
Feedback_Score          0
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [58]:
for i in ['Gender','City','Country']:
    df[i] = df[i].fillna(df[i].mode()[0])

In [63]:
df.isnull().sum()

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    0
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

In [62]:
df['Last_Purchase_Date'] = df['Last_Purchase_Date'].ffill()

In [64]:
df.isnull().sum()

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    0
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

**Fixing inconsistent datatypes**

In [65]:
df['Gender'].unique()

array(['m ', 'M', 'F', 'FEMALE', 'f ', 'male', 'MALE', 'female'],
      dtype=object)

In [71]:
df['Gender'] = df['Gender'].str.lower().str.strip()

In [72]:
df['Gender'].unique()

array(['m', 'f', 'female', 'male'], dtype=object)

In [79]:
df['Gender'] = df['Gender'].replace({'Male':'male','Female':'female'})

In [80]:
df['Gender'].unique()

array(['male', 'female'], dtype=object)

In [82]:
df['City'].unique()

array([' KOLKATA ', ' Kolkata ', ' hyderabad ', ' CHENNAI ', ' kolkata ',
       ' BANGALORE ', ' Hyderabad ', ' HYDERABAD ', ' Mumbai ',
       ' chennai ', ' Delhi ', ' bangalore ', ' Bangalore ', ' delhi ',
       ' Chennai ', ' MUMBAI ', ' DELHI ', ' mumbai '], dtype=object)

In [85]:
df['City'].str.title().str.strip().unique()

array(['Kolkata', 'Hyderabad', 'Chennai', 'Bangalore', 'Mumbai', 'Delhi'],
      dtype=object)

In [87]:
df['City'] = df['City'].str.title().str.strip()

In [88]:
df['City'].unique()

array(['Kolkata', 'Hyderabad', 'Chennai', 'Bangalore', 'Mumbai', 'Delhi'],
      dtype=object)

In [89]:
df['Country'].unique()

array(['India', 'india', 'InDia', 'IND'], dtype=object)

In [91]:
df['Country'] = df['Country'].str.title()

In [92]:
df['Country'].unique()

array(['India', 'Ind'], dtype=object)

In [93]:
df['Country'] = df['Country'].replace({'Ind':'India'})

In [94]:
df['Country'].unique()

array(['India'], dtype=object)

In [95]:
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,male,52.0,Kolkata,26-06-2025,17-05-2025,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,male,51.0,Kolkata,17-02-2021,22-07-2025,44152.0,2.0,owensanthony@example.com,1080761560,India
2,CUST3754,Brittney Martinez,female,62.0,Hyderabad,05-11-2023,08-12-2024,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,female,40.0,Hyderabad,13-03-2022,02-10-2025,39674.0,1.0,berrynancy@example.org,8228064204,India
4,CUST5683,Matthew Carroll,female,41.0,Chennai,05-04-2024,15-12-2024,24268.0,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10194,CUST6146,Cody Thompson,female,40.0,Kolkata,21-08-2024,26-10-2024,35101.0,1.0,mitchellrivera@example.net,6380823112,India
10195,CUST10767,Robert Lewis,female,35.0,Delhi,08-12-2020,25-01-2025,24167.0,9.0,barrycrane@example.net,5004696571,India
10197,CUST6315,Joshua Martinez,male,25.0,Hyderabad,15-02-2022,11-01-2025,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,female,55.0,Kolkata,16-03-2021,14-05-2025,18827.0,10.0,dawn84@example.org,2987564247,India
10199,CUST6588,David Potter,female,34.0,Hyderabad,12-10-2020,27-06-2025,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9177 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                9177 non-null   object
 2   Gender              9177 non-null   object
 3   Age                 9177 non-null   float64
 4   City                9177 non-null   object
 5   Signup_Date         9177 non-null   object
 6   Last_Purchase_Date  9177 non-null   object
 7   Purchase_Amount     9177 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               9177 non-null   object
 10  Phone_Number        9177 non-null   int64
 11  Country             9177 non-null   object
dtypes: float64(3), int64(1), object(8)
memory usage: 932.0+ KB

In [98]:
df.isnull().sum()

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    0
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

**Handling duplicates**

**Handling Duplicates**

In [99]:
df[df.duplicated()]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
1956,CUST8512,Matthew Roberts,male,49.0,Bangalore,03-04-2023,08-10-2024,40325.0,1.0,donna18@example.org,1319901506,India
1974,CUST6647,Julie Padilla,female,54.0,Delhi,13-12-2021,12-03-2025,13217.0,10.0,washingtondavid@example.net,2514229747,India
2032,CUST2755,Casey Campbell,male,43.0,Hyderabad,01-12-2023,04-11-2024,11778.0,3.0,joseph49@example.com,3844741384,India
2110,CUST7014,Phillip Rodriguez,male,57.0,Hyderabad,18-07-2021,22-01-2025,24268.0,1.0,mooremonique@example.com,1392088762,India
2381,CUST5472,Linda Patrick,male,28.0,Kolkata,15-09-2025,27-07-2025,23277.0,7.0,ebryan@example.net,6356542249,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10140,CUST4367,Amber Kennedy,female,61.0,Bangalore,05-11-2023,10-01-2025,40711.0,8.0,kellifox@example.com,5600790669,India
10158,CUST1317,Ashley Hall,male,55.0,Bangalore,14-01-2021,26-10-2024,15990.0,9.0,markhardin@example.net,6840741983,India
10182,CUST1740,Eric Rush,female,38.0,Kolkata,12-10-2023,05-12-2024,12155.0,2.0,llee@example.org,3093645885,India
10185,CUST7439,Kara Gallegos,male,35.0,Kolkata,15-08-2023,27-09-2025,46864.0,2.0,gregoryanderson@example.org,923465413,India
10199,CUST6588,David Potter,female,34.0,Hyderabad,12-10-2020,27-06-2025,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [111]:
df[df.duplicated()].shape

(0, 12)

In [101]:
df.drop_duplicates(inplace = True)

In [102]:
df[df.duplicated()].shape

(0, 12)

In [103]:
df['Customer_ID'].value_counts()

Customer_ID
CUST9534    2
CUST4196    2
CUST5341    2
CUST2510    2
CUST1002    2
           ..
CUST7618    1
CUST2436    1
CUST5982    1
CUST5432    1
CUST4812    1
Name: count, Length: 9000, dtype: int64

In [104]:
df[df['Customer_ID']== 'CUST4196']

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
380,CUST4196,Erica Lane,female,59.0,Kolkata,28-07-2022,22-11-2024,2793.0,4.0,jcarter@example.com,2106988000,India
6342,CUST4196,Erica Lane,female,59.0,Kolkata,28-07-2022,18-12-2024,2793.0,4.0,jcarter@example.com,2106988000,India

In [110]:
df.drop_duplicates(subset = ['Customer_ID'],keep = "first",inplace = True)

**Correcting Datatypes**

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9000 entries, 0 to 10198
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9000 non-null   object
 1   Name                9000 non-null   object
 2   Gender              9000 non-null   object
 3   Age                 9000 non-null   int64
 4   City                9000 non-null   object
 5   Signup_Date         9000 non-null   datetime64[ns]
 6   Last_Purchase_Date  9000 non-null   object
 7   Purchase_Amount     9000 non-null   float64
 8   Feedback_Score      9000 non-null   float64
 9   Email               9000 non-null   object
 10  Phone_Number        9000 non-null   int64
 11  Country             9000 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(2), object(7)
memory usage: 914.1+ KB

In [114]:
df['Age'] = df['Age'].astype('int64')

In [117]:
df['Signup_Date'] = pd.to_datetime(df['Signup_Date'], format='%d-%m-%Y')

In [119]:
df['Last_Purchase_Date'] = pd.to_datetime(df['Last_Purchase_Date'], format='%d-%m-%Y')

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9000 entries, 0 to 10198
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9000 non-null   object
 1   Name                9000 non-null   object
 2   Gender              9000 non-null   object
 3   Age                 9000 non-null   int64
 4   City                9000 non-null   object
 5   Signup_Date         9000 non-null   datetime64[ns]
 6   Last_Purchase_Date  9000 non-null   datetime64[ns]
 7   Purchase_Amount     9000 non-null   float64
 8   Feedback_Score      9000 non-null   float64
 9   Email               9000 non-null   object
 10  Phone_Number        9000 non-null   int64
 11  Country             9000 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(6)
memory usage: 914.1+ KB